apiVersion: v1
kind: Namespace
metadata:
  name: kuard-ns1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kuard
  name: kuard
  namespace: kuard-ns1
spec:
  replicas: 5
  selector:
    matchLabels:
      app: kuard
  template:
    metadata:
      labels:
        app: kuard
    spec:
      containers:
      - image: gcr.io/kuar-demo/kuard-amd64:1
        name: kuard
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kuard-srv
  name: kuard-srv
  namespace: kuard-ns1
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
    nodePort: 30435
  selector:
    app: kuard
  type: NodePort
